### ISSUE TITLE
Support for extended limits

### ISSUE THREAD

**Issue by fragglet** [fragglet/wadptr#11]
Boom and other source ports support extensions to the SIDEDEFS and BLOCKMAP limits to make use of the full 16-bit range (vanilla uses signed integers, only giving 15-bits). So we should add options to support these.

**Comment by Kroc** [comment]
How does wadptr currently handle formats it doesn't understand? I'm worried that if I throw this at a large collection of WADs spanning 25 years, it's going to unwittingly break some (the old wadptr did)

**Comment by fragglet** [comment]
Yep, I can believe that. The old codebase had a lot of baked in assumptions and was written when I was a lot younger and didn't think about this kind of thing. Obviously I can't promise there aren't any bugs still in there, but I've been doing a *lot* of cleanup over the past few weeks with the new 3.x series. 
In particular there are a lot more sanity checks in place to make sure that it never produces a corrupted WAD. If you want to give it another try I'd love to hear about your experience. Maybe try it on a smaller number of WADs first to get some confidence before you go compressing your entire collection. If you find any bugs please do tell me because I want to fix them.

**Comment by fragglet** [comment]
This was added in the 3.3 release.
