### ISSUE TITLE
Failure on MULTIVERSE.WAD

### ISSUE THREAD

**Issue by Kroc** [fragglet/wadptr#15]
https://www.doomworld.com/forum/topic/115093-e1m1-multiverse-release-24/
https://www.doomworld.com/idgames/levels/doom2/Ports/m-o/multiverse
```
Adding: LINEDEFS       Deferred... (0%)
Adding: SIDEDEFS       PackingRebuildSidedefs: LINEDEFS lump (#1244) is 4634 bytes, not a multiple of 16
```

**Comment by fragglet** [comment]
This appears to be because the WAD contains a mixture of Doom-format and Hexen-format maps. wadptr assumes that if the WAD contains any BEHAVIOR lumps then all the maps must be Hexen format.
