### ISSUE TITLE
WAD *increases* in size - Planisf2.wad

### ISSUE THREAD

**Issue by Kroc** [fragglet/wadptr#20]
https://www.doomworld.com/forum/topic/61701
```
Adding: D_RUNNIN       Storing (0%), done.
Adding: MAP01          Empty (0%).
Adding: THINGS         Storing (0%), done.
Adding: LINEDEFS       Deferred... (0%)
Adding: SIDEDEFS       Packing (-1%), done.
Adding: VERTEXES       Storing (0%), done.
Adding: SECTORS        Storing (0%), done.

Merging identical lumps... done.
*** __planisf2 - Copy.wad is -8910 bytes smaller (0%) ***
```
Notice how SIDEDEFS packing goes to -1%!

File sizes:
- original: 1,564,389 bytes
- modified: 1,573,299 bytes

**Comment by fragglet** [comment]
Not a bug (this is because wadptr is cautious about sidedefs on special lines), but I have added a new section to the manual to explain why this happens.

**Comment by Kroc** [comment]
Yes, I expected that it's not a problem but you should perhaps fix the ending message to say "bytes bigger" instead of smaller. Wadptr could have a switch for "don't overwrite if larger" as most PNG optimizers typically have.

**Comment by fragglet** [comment]
Added a clearer message, thanks!
